config/routes.rb
Rails.application.routes.draw do  

	root "posts#index"
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  
  resources :posts do
  	resources :comments
  end  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Post, Comment]
    return unless user.present?
    can :manage, [Post, Comment], user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :comment_text, :presence => true
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :presence => true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    post = Post.find(params[:post_id])
    @comments = post.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
  end

  # GET /comments/new
  def new
    post = Post.find(params[:post_id])
    @comment = post.comments.build(user_id: current_user.id)
  end

  # GET /comments/1/edit
  def edit
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    respond_to do |format|
      format.js {}
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to([@comment.post, @comment], notice: 'Comment was successfully created.') }
        format.js {}
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment = Comment.find_by(id: params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to([@comment.post, @comment], notice: 'Comment was successfully updated.') }
        format.js {}
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post }
      format.json { head :no_content }
    end
  end

  private    
    def comment_params
      params.require(:comment).permit(:comment_text, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.includes(:user)
  end

  # GET /posts/new
  def new
    @post = Post.new(user_id: current_user.id)
  end

  # GET /posts/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content_text, :content_url, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
	 :user
	end

	def resource
	  @resource ||= User.new
	end

	def devise_mapping
	  @devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="form-style-2">
  <% comment = @comment || comment %>
  <%= form_for([comment.post, comment], :remote => true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_area :comment_text, id: :comment_comment_text, class: "textarea-field" %>
    </div>  

    <%= form.hidden_field :post_id %>
    <%= form.hidden_field :user_id %>

    <div class="actions">
      <%= form.submit "Post Comment" %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<div class="form-style-3">
	<% if comments.size != 0 %>
		<div class="form-style-2-heading">Comments</div>
		<div id="comments">
		  <% comments.each do |comment| %>
		  	<div id="comment_<%= comment.id %>">
			    <div class="comment-info">
			      <strong><%= comment.user.username %>:</strong> <%= comment.comment_text %>
			    </div>
			    <div>
			    	<% if can? :manage, comment %>
				      <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), remote: true, id: "edit_#{comment.id}" %>
				      <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
				    <% end %>  
			    </div>
			  </div>  
		    <br>
		  <% end %>
		</div>
	<% end %>	

	<% if can? :create, Comment %>
		<strong>Add Your Comment:</strong>
		<%= render 'comments/form', comment: post.comments.build(user_id: current_user.id) %>
	<% end %>	

</div>

app/views/comments/create.js.erb
$("#comments").append("<div id='comment_<%= @comment.id%>'></div>");
$("#comment_<%= @comment.id%>").append('<div><%= j @comment.user.username %>: <%= j @comment.comment_text %></div><div><%= link_to "Edit", edit_post_comment_path(@comment.post, @comment), remote: true %> <%= link_to "Destroy", [@comment.post, @comment], method: :delete, data: { confirm: "Are you sure?" } %></div><br>')
$("#comment_comment_text").val("")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.post, @comment] %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/edit.js.erb
$("#comment_<%= @comment.id %>").append("<%= j render 'form', comment: @comment %>")

app/views/comments/index.html.erb
<table>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.username %>: </td>
        <td><%= comment.comment_text %></td>
        
        <td><%= link_to 'Show', [comment.post, comment] %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %></td>
        <td><%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Comment', new_post_comment_path %> | <%= link_to 'Back', posts_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@comment.post, @comment) %> |
<%= link_to 'Back', post_comments_path(@comment.post) %>

app/views/comments/update.js.erb
$("#comment_<%= @comment.id %>").html('<div><strong><%= j @comment.user.username %>:</strong> <%= j @comment.comment_text %></div><div><%= link_to "Edit", edit_post_comment_path(@comment.post, @comment), remote: true %> <%= link_to "Delete", [@comment.post, @comment], method: :delete, data: { confirm: "Are you sure?" } %></div>')

$("#comment_comment_text").val("")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta charset='utf-8'>
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "users/shared/links" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: "content-label" %>
    <%= form.text_field :title, id: :post_title, class: "input-field" %>
  </div>

  <div class="form-group">
    <%= form.label :content_text, class: "content-label" %>
    <%= form.text_area :content_text, id: :post_content_text, class: "textarea-field" %>
  </div>

  <div class="form-group">
    <%= form.label :content_url, class: "content-label" %>
    <%= form.text_field :content_url, id: :post_content_url, class: "input-field" %>
  </div>

  <%= form.hidden_field :user_id %>

  <div class="btn-submit wo-label">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='form-style-2'>
	<%= render 'form', post: @post %>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
$(".content-div").append("<div class='form-style-2'><%= j render 'form', post: @post %></div>")

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="form-style-3">
  <div class="form-style-2-heading">Posts</div>
  <% if can? :create, Post %>
    <%= link_to '<input type="button" value="New Post">'.html_safe, new_post_path %>
  <% end %>
  <br>
  <br>
  <% @posts.each do |post| %>
    <div class="content-div">
      <h2><%= post.content_url != '' ? (link_to post.title, post.content_url) : (link_to post.title, post) %></h2>

      <%= link_to 'Comments', post %>
      <% if can? :manage, post %>
        | <%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
      <% end %>
    </div>        
  <% end %>
</div>  

app/views/posts/new.html.erb
<div class="form-style-2">
  <div class="form-style-2-heading">New Post</div>
	<%= render 'form', post: @post %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="form-style-3">
  <div class="form-style-2-heading"><%= @post.title %></div>
  <div class="content-div">
	  <div class="content"><%= @post.content_text %></div>
	  <div class="post-info">by <strong><%= @post.user.username.capitalize %></strong></div>	  
	</div>	
	<% if can? :manage, @post %>
		<%= link_to 'Edit', edit_post_path(@post), remote: true %> | 
	<% end %>
	<%= link_to 'Back', posts_path %>

	<%= render "comments/index", comments: @comments, post: @post %>	
	
</div>	

app/views/users/shared/_links.html.erb
<div id='cssmenu' class="align-right">
	<ul>
		<%- if devise_mapping.registerable? && controller_name != 'registrations' && !current_user %>
			<li>
		    <%= link_to '<span>Sign Up</span>'.html_safe, new_registration_path(resource_name) %>			
	  	</li>	
	  <% end -%>		  
	  <% if controller_name != 'sessions' %>
	  	<li>
		 		<% if user_signed_in? %>
				  <%= link_to('<span>Logout</span>'.html_safe, destroy_user_session_path, method: :delete) %>       
				<% else %>
				  <%= link_to('<span>Login</span>'.html_safe, new_user_session_path)  %>  
				<% end %>
			</li>	
		<% end %>				   	
	</ul>
</div>